### ISSUE TITLE
Corresponding snapshot doesn't exist

### ISSUE THREAD

**Issue by RobinMalfait** [asvetliakov/snapshot-tools#1] opened 2017-03-25 19:52 UTC
My `__tests__` folder are deeply nested inside the `./src/` directory. Any idea on how to configure my settings to make it work?

Thanks in advance!

**Comment by asvetliakov** [comment] 2017-03-25 20:07
Hello Robin. Can you give me your files tree example?

**Comment by RobinMalfait** [comment] 2017-03-25 22:35
Sure hold on.

![](http://d.rbn.nu/ktqO.png)

this is just one layer. Apart from that, this is an example test

```js
/* global describe, beforeEach, it, expect */
import {
  requestType,
  successType,
  failedType,
  oneOf,
  oneOfDelimiter,
} from '../types';

it('should create a request type', () => {
  expect(requestType('ACTION_TYPE')).toMatchSnapshot();
});

it('should create a success type', () => {
  expect(successType('ACTION_TYPE')).toMatchSnapshot();
});

it('should create a failed type', () => {
  expect(failedType('ACTION_TYPE')).toMatchSnapshot();
});

it('should create a combined type', () => {
  expect(oneOf(['ACTION_ONE', 'ACTION_TWO'])).toMatchSnapshot();
});

it('should have a oneOfDelimiter', () => {
  expect(oneOfDelimiter).toMatchSnapshot();
});

```

**Comment by asvetliakov** [comment] 2017-03-25 22:39
For your example it must just work. Did you set any config options? Remove them & reload vscode

Ah... try to wrap your ```it()``` calls into one ```describe()``` call and see if it works

**Comment by asvetliakov** [comment] 2017-03-25 22:47
Your example works for me either with/without describe. Which OS are you using?
![screen shot 2017-03-25 at 23 46 35](https://cloud.githubusercontent.com/assets/8881674/24326738/5cc5e278-11b5-11e7-9069-f8a1faac957b.png)


Did you actually run jest to update/produce snapshots? It will warn you if snapshot file doesn't exist or there is no such snapshot in the snapshot file.

**Comment by RobinMalfait** [comment] 2017-03-25 22:50
I did not set any configs, and my jest test is working as expected and snapshots are being generated. I do use `create-react-app`, maybe that's the problem?

https://github.com/facebookincubator/create-react-app

**Comment by RobinMalfait** [comment] 2017-03-25 22:51
```
Test Suites: 27 passed, 27 total
Tests:       85 passed, 85 total
Snapshots:   37 passed, 37 total
Time:        4.53s
Ran all test suites.
```

**Comment by asvetliakov** [comment] 2017-03-25 23:00
No, the plugin must be independent about any app generators or tools. Are you using Windows?

**Comment by RobinMalfait** [comment] 2017-03-28 20:05
Nope, I'm on a mac. Very strange. Could you send me that example project you got there? So I can check if that works on my machine?

**Comment by RobinMalfait** [comment] 2017-03-28 20:08
**Note**: ok it needs a 'describe' block around it. Is there a way to bypass that? 
Because by default it will search for 'describeName testName snapshotIndex', and if you don't have a describe block, it will use "test". So that as a default might be nice

**Comment by asvetliakov** [comment] 2017-03-28 20:17
You can create test project similar to my screenshot above (i.e. just single test file under __tests__ directory with snapshot assertion for simple object). Even no ```package.json``` needed, then run jest globally.

It doesn't need describe blocks to be presented:

![screen shot 2017-03-28 at 22 16 51](https://cloud.githubusercontent.com/assets/8881674/24425384/557616ae-1404-11e7-9e7f-7232042aecdf.png)

**Comment by asvetliakov** [comment] 2017-03-28 20:28
Can you send me reproducible example? I'm not sure how can i help 🐱

**Comment by asvetliakov** [comment] 2017-10-27 01:13
Closing, feel free to reopen if needed.

**Closed as completed by asvetliakov** 2017-10-27 01:13 UTC

**Comment by RobinMalfait** [comment] 2017-10-27 06:53
Oops totally forgot about this. Meaning I think it is fixed? Haha sorry!

**Comment by asvetliakov** [comment] 2017-10-27 12:41
@RobinMalfait Much like so. Anyway, try the new language service plugin https://github.com/asvetliakov/typescript-snapshots-plugin
